name: Coverage Check
on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Root
      - name: Clean install (root)
        run: |
          rm -rf node_modules package-lock.json
          npm i

      # Backend
      - name: Clean install (backend)
        run: |
          rm -rf backend/node_modules backend/package-lock.json
          npm install --prefix backend

      # Run test
      - name: Check coverage
        run: npm run test:coverage
